[js.landing.discord]
loading = "Повис на загрузке.."
joining = "Собирается хуярить кубики"
joined = "Хуярит кубики"

[js.discord]
waiting = "Ждём клиент.."
state = "На сервере: {shortId}"
inSettings = "broke client :("
stateInSettings = "In settings"
inMainMenu = "Ну тип новости чекает"
stateInMainMenu = "Залип в главное меню"
stateInMainMenuIcon = "mainmenu"